import os


def safe_value(data, key):
    if key in data and data[key] != "":
        return str(data[key])
    return "Not provided"


def build_markdown_report(data):
    report_id = safe_value(data, "Report ID")
    report_type = safe_value(data, "Report Type")
    report_date = safe_value(data, "Report Date")
    report_time = safe_value(data, "Report Time")
    anonymous = safe_value(data, "Anonymous")

    reporter_name = safe_value(data, "Reporter Name")
    reporter_email = safe_value(data, "Reporter Email")
    reporter_phone = safe_value(data, "Reporter Phone")
    reporter_role = safe_value(data, "Reporter Role")

    incident_date = safe_value(data, "Incident Date")
    incident_time = safe_value(data, "Incident Time")
    incident_location = safe_value(data, "Incident Location")
    incident_description = safe_value(data, "Incident Description")

    accused_name = safe_value(data, "Accused Name")
    accused_role = safe_value(data, "Accused Role")
    witnesses = safe_value(data, "Witnesses")
    resolution_request = safe_value(data, "Resolution Request")
    resolution_comment = safe_value(data, "Resolution Comment")

    if anonymous == "True":
        reporter_name = "Anonymous"
        reporter_email = "Hidden"
        reporter_phone = "Hidden"
        reporter_role = "Hidden"

    markdown_text = f"""# EthicalReport 1.0

## Report Information
- **Report ID:** {report_id}
- **Report Type:** {report_type}
- **Report Date:** {report_date}
- **Report Time:** {report_time}
- **Anonymous Report:** {anonymous}

---

## Reporter Information
- **Reporter Name:** {reporter_name}
- **Reporter Email:** {reporter_email}
- **Reporter Phone:** {reporter_phone}
- **Reporter Role:** {reporter_role}

---

## Incident Information
- **Incident Date:** {incident_date}
- **Incident Time:** {incident_time}
- **Incident Location:** {incident_location}

### Incident Description
{incident_description}

---

## Reported Person Information
- **Name:** {accused_name}
- **Role / Position:** {accused_role}

---

## Witnesses
{witnesses}

---

## Requested Resolution Process
{resolution_request}

---

## Additional Comments
{resolution_comment}

## Notes
This report was generated by EthicalReport.
Please handle this document carefully to protect privacy and preserve documentation integrity.
"""
    return markdown_text


def save_markdown_report(data):
    print("Starting markdown report generation...")

    report_id = safe_value(data, "Report ID")

    if report_id == "Not provided":
        file_name = "ER-report.md"
    else:
        file_name = f"{report_id}.md"

    print("Building markdown text...")
    markdown_text = build_markdown_report(data)

    print("Saving file...")
    with open(file_name, "w", encoding="utf-8") as file:
        file.write(markdown_text)

    print("Report saved successfully!")
    print("Saved as:", os.path.abspath(file_name))